# ============================================================================
# ⚠️  READ-ONLY REFERENCE FILE - DO NOT EDIT THIS FILE  ⚠️
# ============================================================================
# This is a TEMPLATE/REFERENCE snippet for hackathon candidates.
# 
# TO USE THIS CODE:
#   1. Create a NEW file (e.g., solution.py, my_implementation.py)
#   2. Copy the function signatures you need
#   3. Implement your solution in the NEW file
#
# DO NOT modify this file directly!
# ============================================================================

"""
Division Operations - Code Snippet

This snippet provides a template for implementing division functions.
Candidates should complete the implementation based on the requirements.
"""


def divide_two_numbers(a: int, b: int) -> float:
    """
    Divide a by b and return the result.
    
    Args:
        a: Dividend
        b: Divisor
        
    Returns:
        Quotient of a divided by b
        
    Raises:
        ZeroDivisionError: If b is zero
        
    Example:
        >>> divide_two_numbers(10, 2)
        5.0
        >>> divide_two_numbers(7, 2)
        3.5
    """
    # TODO: Implement division with zero check
    pass


def integer_divide(a: int, b: int) -> tuple:
    """
    Perform integer division and return quotient and remainder.
    
    Args:
        a: Dividend
        b: Divisor
        
    Returns:
        Tuple of (quotient, remainder)
        
    Raises:
        ZeroDivisionError: If b is zero
        
    Example:
        >>> integer_divide(17, 5)
        (3, 2)
        >>> integer_divide(10, 3)
        (3, 1)
    """
    # TODO: Implement integer division
    # Hint: Use // for quotient and % for remainder
    pass


def safe_divide(a: int, b: int, default: float = 0.0) -> float:
    """
    Divide with a default value for division by zero.
    
    Args:
        a: Dividend
        b: Divisor
        default: Value to return if b is zero
        
    Returns:
        Quotient of a/b, or default if b is zero
        
    Example:
        >>> safe_divide(10, 2)
        5.0
        >>> safe_divide(10, 0)
        0.0
        >>> safe_divide(10, 0, default=-1)
        -1
    """
    # TODO: Implement safe division
    pass


def average(numbers: list) -> float:
    """
    Calculate the average of a list of numbers.
    
    Args:
        numbers: List of numbers
        
    Returns:
        Average (mean) of the numbers
        
    Raises:
        ValueError: If list is empty
        
    Example:
        >>> average([1, 2, 3, 4, 5])
        3.0
        >>> average([10, 20])
        15.0
    """
    # TODO: Implement average calculation
    # Hint: Handle empty list case
    pass
