# ============================================================================
# ⚠️  READ-ONLY REFERENCE FILE - DO NOT EDIT THIS FILE  ⚠️
# ============================================================================
# This is a TEMPLATE/REFERENCE snippet for hackathon candidates.
# 
# TO USE THIS CODE:
#   1. Create a NEW file (e.g., solution.py, my_implementation.py)
#   2. Copy the function signatures you need
#   3. Implement your solution in the NEW file
#
# DO NOT modify this file directly!
# ============================================================================

"""
Multiplication Operations - Code Snippet

This snippet provides a template for implementing multiplication functions.
Candidates should complete the implementation based on the requirements.
"""


def multiply_two_numbers(a: int, b: int) -> int:
    """
    Multiply two integers and return the result.
    
    Args:
        a: First integer
        b: Second integer
        
    Returns:
        Product of a and b
        
    Example:
        >>> multiply_two_numbers(4, 5)
        20
        >>> multiply_two_numbers(-3, 7)
        -21
    """
    # TODO: Implement multiplication
    pass


def multiply_list(numbers: list) -> int:
    """
    Multiply all numbers in a list and return the product.
    
    Args:
        numbers: List of integers to multiply
        
    Returns:
        Product of all numbers in the list
        
    Example:
        >>> multiply_list([1, 2, 3, 4])
        24
        >>> multiply_list([5, 0, 10])
        0
    """
    # TODO: Implement list multiplication
    # Hint: Consider edge cases like empty list and zero
    pass


def power(base: int, exponent: int) -> int:
    """
    Calculate base raised to the power of exponent.
    
    Args:
        base: The base number
        exponent: The exponent (must be non-negative)
        
    Returns:
        base ^ exponent
        
    Raises:
        ValueError: If exponent is negative
        
    Example:
        >>> power(2, 3)
        8
        >>> power(5, 0)
        1
    """
    # TODO: Implement power function without using ** operator
    # Hint: Use a loop or recursion
    pass
