# ============================================================================
# ⚠️  READ-ONLY REFERENCE FILE - DO NOT EDIT THIS FILE  ⚠️
# ============================================================================
# This is a TEMPLATE/REFERENCE snippet for hackathon candidates.
# 
# TO USE THIS CODE:
#   1. Create a NEW file (e.g., solution.py, my_implementation.py)
#   2. Copy the function signatures you need
#   3. Implement your solution in the NEW file
#
# DO NOT modify this file directly!
# ============================================================================

"""
Subtraction Operations - Code Snippet

This snippet provides a template for implementing subtraction functions.
Candidates should complete the implementation based on the requirements.
"""


def subtract_two_numbers(a: int, b: int) -> int:
    """
    Subtract b from a and return the result.
    
    Args:
        a: First integer (minuend)
        b: Second integer (subtrahend)
        
    Returns:
        Difference of a and b (a - b)
        
    Example:
        >>> subtract_two_numbers(10, 3)
        7
        >>> subtract_two_numbers(5, 8)
        -3
    """
    # TODO: Implement subtraction
    pass


def subtract_from_total(total: int, *values) -> int:
    """
    Subtract multiple values from a total.
    
    Args:
        total: Starting value
        *values: Values to subtract from total
        
    Returns:
        Result after subtracting all values
        
    Example:
        >>> subtract_from_total(100, 20, 30, 10)
        40
        >>> subtract_from_total(50)
        50
    """
    # TODO: Implement multiple subtraction
    pass


def safe_subtract(a: int, b: int, allow_negative: bool = True) -> int:
    """
    Subtract with optional constraint on negative results.
    
    Args:
        a: First integer
        b: Second integer
        allow_negative: If False, return 0 instead of negative results
        
    Returns:
        Difference, or 0 if result is negative and allow_negative is False
        
    Example:
        >>> safe_subtract(5, 3, allow_negative=True)
        2
        >>> safe_subtract(3, 5, allow_negative=False)
        0
    """
    # TODO: Implement safe subtraction
    pass
